Feature/aos 4777 ao adm recreate config
Skatteetaten/ao pull request #183
Opened 2020-08-25 13:09 UTC by RuneOfferdal

Etter å ha vært innom hashing og vurdert om det var mulig å skille dynamiske "sesjons"-konfigurasjoner fra mer varige, så har jeg valgt en enklere løsning i denne omgang:

- Gir opplysning om "ao adm recreate-config" ved feilsituasjon i ao login
- Versjonstag i .ao.json som gir spørsmål om oppdatering dersom ao har en annen versjon enn filen er laget med.

2020-08-26 08:42 UTC, oyvinder requested changes

2020-08-26 08:44 UTC, oyvinder commented
Vi må ha mulighet til å automatisk svare ja eller nei på spørsmål om recreate-config.
Er det riktig at de som svarer nei skal bli spurt på nytt hver gang de kjører ao?

2020-08-26 08:52 UTC, RuneOfferdal commented on cmd/root.go
> +		fmt.Printf("\nThe current ao config is made with an older version of ao.\n")
Stemmer.  Det riktige skal være "another" istedenfor "older".  Fikser.

2020-08-26 08:56 UTC, RuneOfferdal commented on cmd/root.go
> +		message := "Do you want to recreate the ao config with default values (recommended)?"
Ok, forsøker å presisere her uten å komme med avhanding.  Fikser.

2020-08-26 08:56 UTC, RuneOfferdal commented
> Vi må ha mulighet til å automatisk svare ja eller nei på spørsmål om recreate-config.
> Er det riktig at de som svarer nei skal bli spurt på nytt hver gang de kjører ao?

2020-08-26 10:40 UTC, RuneOfferdal commented
> > Vi må ha mulighet til å automatisk svare ja eller nei på spørsmål om recreate-config.
> > Er det riktig at de som svarer nei skal bli spurt på nytt hver gang de kjører ao?

Har diskutert dette, og det kommer en fiks:
Mekanismen for oppdatering tar nå hensyn til "token"-flagget, og det er i tillegg laget et hidden flagg "autoanswer-recreate-config" der man kan velge [y, n] som svar på spørsmålet. 
De som svarer nei må enten leve med å svare på spørsmålet, spesifisere flagg som angitt over eller manuelt oppdatere versjon i .ao.json (på eget ansvar)

2020-08-27 07:33 UTC, stromland approved these changes

2020-08-27 11:46 UTC, oyvinder approved these changes

2020-08-27 11:55 UTC, merged