Feature/aos 5325 vault secrets
Skatteetaten/ao pull request #201
Opened 2021-03-09 13:19 UTC by RuneOfferdal

Inneholder fikser for resten av ao vault *, slik at alle ao vault-kall går mot gobo.

Gammel kode er ryddet vekk.

2021-03-09 14:19 UTC, jarlehansen requested changes

2021-03-09 14:19 UTC, jarlehansen commented on pkg/client/vault.go
> +		affiliations(name: $affiliation) {
bruk `names` her, `name` er deprecated

2021-03-09 15:08 UTC, RuneOfferdal commented on pkg/client/vault.go
> +		affiliations(name: $affiliation) {
Fixed

2021-03-11 20:54 UTC, oyvinder approved these changes

2021-03-12 09:27 UTC, merged

2021-03-12 11:37 UTC, RuneOfferdal commented on pkg/client/vault.go
> +const addVaultSecretsRequestString = `mutation addVaultSecrets ($addVaultSecretsInput: AddVaultSecretsInput!){
Det er en konvensjon. Dette gir jo litt ekstra informasjon bl.a. i debuglogging.