Feature/aos 6618 flytte au inn i ao
Skatteetaten/ao pull request #238
Opened 2022-04-25 13:03 UTC by kris456

2022-04-25 13:05 UTC, kris456 commented on cmd/dev.go
> +	namespace := spec.GetString("namespace")
Avhengig av denne PRen i boober:
https://github.com/Skatteetaten/boober/pull/538

2022-04-26 08:44 UTC, stromland approved these changes

2022-04-26 08:44 UTC, stromland commented on cmd/dev.go
> +//go:build !windows
Kan du legge inn en kommentar her med årsaken til at dette må gjøres?

2022-04-26 08:44 UTC, kris456 commented on cmd/dev.go
> +//go:build !windows
will do

2022-04-26 12:21 UTC, RuneOfferdal requested changes
Har noen kommentarer der jeg mener de fleste bør tas til følge før merge (spesielt dem i dev.go)

2022-04-26 12:21 UTC, RuneOfferdal commented on cmd/dev.go
> +	return allSpecs[0], nil
Siden man kan få flere tilslag fra fuzzy-matchingen blir denne uforutsigbar og litt skummel.  getSpec bør feile dersom det er mer enn én match.  (Dette blir litt som for ao deploy med version-flagg eller ao get spec. Begge de kommandoene bruker også fuzzy-matching og skal feile dersom det er mer enn én match)

Jeg ser at denne er "sikret" av at getFuzzyMatchedResult feiler om det ikke er en eksakt match, men da bør den returnere kun en verdi.

2022-04-26 12:21 UTC, RuneOfferdal commented on cmd/dev.go
> +func getFuzzyMatchedResult(search string, fileNames auroraconfig.FileNames) ([]string, error) {
Siden denne skal returnere kun én verdi, så bør respons være (string, error) istedet.

2022-04-26 12:21 UTC, RuneOfferdal commented on cmd/dev.go
> +	shouldContinue := prompt.Confirm(fmt.Sprintf("Do you wish to rollout ApplicationDeployment %s", matches[0]), true)
Jeg ville tatt ut prompten og ventet med å spørre til man også har sjekket at matchende spec er av type "development".  Se kommentar om prompt lenger opp.

2022-04-26 12:21 UTC, RuneOfferdal commented on cmd/dev.go
> +
Ville ventet med prompt om "Do you wish to rollout ...." til man kommer hit.  
Det er blir litt lite tilfredstillende brukerflyt å be om bekreftelse og så feile fordi man sjekker type= development etterpå.

2022-04-26 12:21 UTC, RuneOfferdal commented on cmd/dev.go
> +	matches, err := getFuzzyMatchedResult(search, fileNames)
getFuzzyMatchedResult kan ihht koden kun returnere en enkelt match.  Da bør det returneres string istedenfor string-array.

2022-04-26 12:23 UTC, RuneOfferdal commented on go.mod
> +	github.com/skatteetaten/architect/v2 v2.6.6-alpha.3
Ville ventet med merge til architect har en stabil versjon (ikke alpha)

2022-04-26 12:47 UTC, kris456 commented on go.mod
> +	github.com/skatteetaten/architect/v2 v2.6.6-alpha.3
ja. Det er jeg som har laget en alpha versjon for å teste ut den nye funksjonaliteten jeg la til. Jeg merger den før denne og oppdaterer versjonen her

2022-04-27 08:17 UTC, kris456 commented on cmd/get.go
> +		split := strings.Split(matches[0], "/")
det var bare noe jeg så i forbifarten. Den brukes kun innenfor scopet if !flagJSON {} og tenkte da at den hørte hjemme der

2022-04-27 08:31 UTC, kris456 commented on cmd/dev.go
> +	rolloutCmd = &cobra.Command{
Det tenker jeg vi kan diskutere i en annen oppgave hvordan det blir eller hva tenker du @stromland ?

2022-04-27 08:32 UTC, kris456 commented on cmd/dev.go
> +func getFuzzyMatchedResult(search string, fileNames auroraconfig.FileNames) ([]string, error) {
fikset

2022-04-27 08:32 UTC, kris456 commented on cmd/dev.go
> +	matches, err := getFuzzyMatchedResult(search, fileNames)
fikset

2022-04-27 09:55 UTC, stromland commented on cmd/dev.go
> +	rolloutCmd = &cobra.Command{
Ja, tenker det er en egen oppgave som vi kan ta senere.

2022-04-27 12:24 UTC, RuneOfferdal commented on cmd/dev.go
> +	rolloutCmd = &cobra.Command{
Den er grei

2022-04-27 12:46 UTC, RuneOfferdal commented on cmd/dev.go
> +
Ser prompten nå er plassert i getSpec istedenfor getFuzzyMatchedAdr.  Fortsatt kommer dermed sjekken av om type = "development" etter at spørsmålet er stilt.

2022-04-27 12:55 UTC, RuneOfferdal commented on cmd/dev.go
> +	allSpecs, err := DefaultAPIClient.GetAuroraDeploySpec([]string{matchedAdr}, !flagNoDefaults, flagIgnoreErrors)
Bruken av flagg er litt ustandard.  Det er ingen tilordning av flagg til rolloutCmd i init() og da er det vanskelig å se at disse flaggene (flagNoDefaults og flagIgnoreErrors) faktisk vil ha noen annen verdi enn default fra der de er definert i denne konteksten.

Jeg ville også vurdert om det skal være mulig å skippe prompt ved å spesifisere disse flaggene tilsvarende som i deploy:
`	rolloutCmd.Flags().BoolVarP(&flagAcceptRollout, "yes", "y", false, "Suppress prompts and accept rollout")`
`	rolloutCmd.Flags().BoolVarP(&flagAcceptRollout, "no-prompt", "", false, "Suppress prompts and accept rollout")`
og så gjøre spørsmålet om rollout avhenging av flagget.

2022-05-02 08:06 UTC, RuneOfferdal approved these changes
Dette ser bra ut.  Non-alpha av architect nå, så er vi good to go.  :-)

2022-05-02 10:21 UTC, kris456 commented
Jeg oppgraderte architect og la til et eksempel

2022-05-04 11:45 UTC, merged